"""Правка моделей под 3.9 дубль 2

Revision ID: ebd15c285f4f
Revises: 0abde6a5acbf
Create Date: 2024-03-29 13:54:15.986130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebd15c285f4f'
down_revision: Union[str, None] = '0abde6a5acbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('full_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('invested_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('fully_invested',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('create_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('full_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('invested_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('fully_invested',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('create_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('create_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('fully_invested',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('invested_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('full_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.alter_column('create_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('fully_invested',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('invested_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('full_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
